    save_best: True
    plot_agents: True
    collect_stats: False

    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./cacla_logs/
      verbose: False
      every_n_seconds: 10


    algorithm:
      seed:
        act: 10
        train: 335
        eval: 983
        q: 123
        explorer: 456
        torch: 789

      max_grad_norm: 0.5

      n_steps: 7000000
      eval_interval: 2
      n_steps_train: 1

      action_noise: 0.1
      n_envs_eval: 50
      n_envs: 1
      nb_evals: 50
      nb_episodes: 10000
      discount_factor: 0.95
      critic_coef: 1
      actor_coef: 1
      actor_type: ContinuousActor
      architecture:
        actor_hidden_size: [12]
        critic_hidden_size: [12]

    gym_env:
      classname: __main__.make_gym_env
      env_name: CartPoleContinuous-v1

    actor_optimizer:
      classname: torch.optim.SGD
      lr: 1e-2

    critic_optimizer:
      classname: torch.optim.SGD
      lr: 1e-2
